chore(ci/cd): update ci/cd

diff --git a/.github/workflows/build-image.yml b/.github/workflows/build-image.yml
--- a/.github/workflows/build-image.yml
+++ b/.github/workflows/build-image.yml
@@ -1,7 +1,16 @@
 name: Build image
 
 on:
-  workflow_dispatch:
+  push:
+    branches:
+      - main
+    tags:
+      - 'backend@*'
+      - 'frontend-server@*'
+      - 'nginx@*'
+      - 'notes-db@*'
+      - 'pgadmin4@*'
+      - 'task-manager@*'
 
 env:
   CI: true
@@ -10,14 +19,31 @@ jobs:
   build-image:
     runs-on: ubuntu-latest
 
+    env:
+      IMAGE_NAME: 'IMAGE_NAME'
+
     steps:
       - name: Checkout 
         uses: actions/checkout@v4
 
-      - uses: actions/download-artifact@v4
-        with:
-          name: changed
-          path: ./changed.txt
+      - name: Extract image name
+        run: |
+          TAG=${{ github.ref_name }}
+          IMAGE_NAME=$(echo $TAG | sed 's/@.*//')
+          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
+
+      - name: Validate image name
+        run: |
+          IMAGE_NAME=${{ env.IMAGE_NAME }}
+          VALID_NAMES=("backend" "frontend-server" "nginx" "notes-db" "pgadmin4" "task-manager")
+          if [[ ! "${VALID_NAMES[@]}" =~ "${IMAGE_NAME}" ]]; then
+            echo "Error: Invalid image name '${IMAGE_NAME}'. Must be one of: ${VALID_NAMES[*]}."
+            exit 1
+          fi
+          echo "Image name is ${IMAGE_NAME}"
+      
+      - name: Display image name
+        run: echo "Image name is ${{ env.IMAGE_NAME }}"
   
       - name: Docker meta
         id: meta
@@ -25,11 +51,12 @@ jobs:
         with:
           # list of Docker images to use as base name for tags
           images: |
-            name/app
-            ghcr.io/username/app            
+            notes-${{ env.IMAGE_NAME }}            
           # generate Docker tags based on the following events/attributes
           tags: |
-            type=semver,pattern={{version}}
+            type=match,pattern=${{ env.IMAGE_NAME }}@(\d.\d.\d),group=1
+          flavor: |
+            latest=true
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -43,8 +70,9 @@ jobs:
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
-          context: .
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
-          file: ./Dockerfile
+          file: ./${{ env.IMAGE_NAME }}/Dockerfile
+          context: ./${{ env.IMAGE_NAME }}
+          target: prod
